name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./auth-service
        run: npm install

      - name: Run SonarCloud Scan
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=poorna-theekshana_Net-Bookings \
            -Dsonar.organization=poorna-theekshana \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=. \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        working-directory: ./auth-service
