name: Run Tests on PR Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.merged == true || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup environment variables
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd auth-service
          npm install

      - name: Run Tests
        run: |
          cd auth-service
          npm test
